### ISSUE TITLE
AutoID

### ISSUE THREAD

**Issue by SD-Hunter** [angeld29/TF2003-qvm#2]
Сделать встроенный autoid включенным по умолчанию, с возможностью выключения. Сейчас сделано наоборот (скорее всего, для совместимости со старыми конфигами, где у людей было id на движение).

**Comment by angeld29** [comment]
имеет смысл переделать спешиал на вкл/выкл автоскана, с включенным автосканом по умолчанию
а ручной скан оставить на алиасах scanXX
