### ISSUE TITLE
Grensound

### ISSUE THREAD

**Issue by SD-Hunter** [angeld29/TF2003-qvm#3]
Сделать автопроигрывание звука для гранат включенным по умолчанию, с возможностью отключения. Сейчас сделано наоборот (для совместимости с конфигами, где звук уже был прописан).

**Comment by angeld29** [comment]
имеет смысл переделать спешиал на вкл/выкл автоскана, с включенным автосканом по умолчанию
а ручной скан оставить на алиасах scanXX
